q40603-proposal-attempt1
yungyuc/nsdhw_21sp pull request #26
Opened 2021-03-24 09:56 UTC by q40603

---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

2021-03-24 10:06 UTC, yungyuc commented
Thanks @q40603 .  It seemed that you created the PR from `master` so that it contains unwanted changeset.  You should have created the PR from `proposal`.  To help you remove the unwanted change, I merged the `proposal` branch with `master`.  Could you do either of the following before I start review your proposal?

1. Pull and rebased to the current `proposal` branch.  Update the PR.
2. Use the new `master` / `proposal`, and create another PR.

2021-03-30 08:19 UTC, q40603 commented
Fix it with rebase.

2021-04-07 10:58 UTC, yungyuc requested changes
Please correct the format and add the missing parts before the proposal due.

2021-04-07 10:58 UTC, yungyuc commented on proposal/q40603/proposal.md
> +
Please add the github link in the proposal.

2021-04-07 10:58 UTC, yungyuc commented on proposal/q40603/proposal.md
> +Proposal for Pairs Trading
The template file uses [reStructuredText](https://docutils.sourceforge.io/rst.html), not markdown.  Is the filename a typo?

If you choose markdown, please reformat the file.

2021-04-07 10:58 UTC, yungyuc commented on proposal/q40603/proposal.md
> +| ![](https://i.imgur.com/ajKsdUc.png)     | ![](https://i.imgur.com/2cPbJ7F.png)    |
If you own the images, it's a good idea to add them here in the proposal directory as records.

2021-04-07 10:58 UTC, yungyuc commented on proposal/q40603/proposal.md
> +### Prerequiement
Now this is markdown.  I am not pretty sure which text format you are trying to use.  It'd be better if you stick with one.

2021-04-07 10:58 UTC, yungyuc commented on proposal/q40603/proposal.md
> +待補
Use English.

2021-04-07 10:58 UTC, yungyuc commented on proposal/q40603/proposal.md
> +(TBD)
Need to add architecture.

2021-04-07 10:58 UTC, yungyuc commented on proposal/q40603/proposal.md
> +(TBD)
Need to add API.

2021-04-07 10:58 UTC, yungyuc commented on proposal/q40603/proposal.md
> +(TBD)
Add engineering.

2021-04-07 10:58 UTC, yungyuc commented on proposal/q40603/proposal.md
> +(TBD)
Add schedule.

2021-04-07 22:57 UTC, yungyuc commented
@q40603 When you finish updating your branch please add comments to let me know I should review again.

2021-04-08 01:11 UTC, q40603 commented
Proposal finished.

2021-04-10 02:38 UTC, yungyuc commented on proposal/q40603/proposal.md
> +![](https://i.imgur.com/gfkwosJ.png)
The equations will be good to be included in a written report or presentation slides.  If you have not done it, you are encouraged to do it.

2021-04-10 02:38 UTC, yungyuc commented on proposal/q40603/proposal.md
> +1. In Numerical Software Development, are there any special design pattern for us to follow?
This is an excellent question.  It's no and yes.  No, the design patterns for numerical, scientific, and engineering codes are are special.  But yes, the codes do use a special selection and combination of the patterns.

There is not a good reference for the numerical design patterns, but I think the patterns used in game design have good resemblance.  You may take a look at https://gameprogrammingpatterns.com/contents.html .

2021-04-10 02:38 UTC, yungyuc commented on proposal/q40603/proposal.md
> +2. What is the best way to moduralize the whole computaion
Your implementation is the starting line of the journey to discover what will be the ways.

2021-04-10 02:38 UTC, yungyuc commented on proposal/q40603/proposal.md
> +3. In numerical computaion, many function relys on the previous function output, can we use stub software testing techinque in Numerical Software Devlopment?
It sounds like a good idea.  I do not see showstopper of using that technique.  Keep in mind that it doesn't solve all problems in the coupling.

2021-04-10 02:40 UTC, yungyuc commented
LGTM.  I will merge once I have all proposal graded.

2021-04-24 12:18 UTC, yungyuc approved these changes

2021-04-24 12:19 UTC, merged