veax-void-proposal-attempt1
yungyuc/nsdhw_21sp pull request #27
Opened 2021-03-29 01:46 UTC by veax-void

---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

2021-04-07 11:03 UTC, yungyuc requested changes

2021-04-07 11:03 UTC, yungyuc commented on proposal/veax-void/README.md
> +[Official PIGS repo](https://github.com/veax-void/nsdhw_21sp/tree/veax-void-proposal)
The project repository should be different from your clone of the homework one.

2021-04-07 11:03 UTC, yungyuc commented on proposal/veax-void/README.md
> +Readme for PIGS or Pixelwise Image Graph Segmentation project developmet.
I like the name!

2021-04-07 11:03 UTC, yungyuc commented on proposal/veax-void/README.md
> +Image processing, especially segmentation tasks are really heavy on computations, but also provide a lot of value.
Please be specific on what value it provides.

2021-04-07 11:03 UTC, yungyuc commented on proposal/veax-void/README.md
> +**TODO**: Make a system dataflow, add charts!
Add system architecture.  It may or may not need a chart.

2021-04-07 11:03 UTC, yungyuc commented on proposal/veax-void/README.md
> +**TODO**: Add API
In the beginning, the API description may be very high-level.

2021-04-07 11:03 UTC, yungyuc commented on proposal/veax-void/README.md
> +**TODO**: TESTS, DOCS, version control, CI/CD
You can itemize what you want to test.

2021-04-07 11:03 UTC, yungyuc commented on proposal/veax-void/README.md
> +- 30 days: Development
A good starting point.  You may add some sub-bullets on what you plan to develop.  Also, put dates on each of the milestones.

2021-04-07 11:03 UTC, yungyuc commented on proposal/veax-void/README.md
> +- 10 days: Testing
Testing should not wait after development.

2021-04-10 02:56 UTC, yungyuc commented
@veax-void please update the proposal itself as soon as possible.

2021-04-10 11:21 UTC, veax-void commented
> @veax-void please update the proposal itself as soon as possible.

Updated! Added fixed readme and first prototype.

2021-04-10 11:31 UTC, yungyuc reviewed
LGTM.  I will merge the PR once finish grading all proposals.

2021-04-10 11:31 UTC, yungyuc commented on proposal/veax-void/README.md
> +- [ ] Memory leakage
Memory leak is hard to detect.  To detect memory error, you need to have a custom memory manager, which you may start with.

2021-04-10 11:31 UTC, yungyuc commented on proposal/veax-void/README.md
> +>- **23.05.21**: Development / Testing
Adding notes for what you want to test will help your development.

2021-04-24 12:19 UTC, yungyuc approved these changes

2021-04-24 12:20 UTC, merged