bhbruce-proposal-reattempt1
yungyuc/nsdhw_21sp pull request #52
Opened 2021-04-11 12:08 UTC by bhbruce

---
A good PR should include the following parts:

- [X] A clear title
- [X] A meaningful message for PR, as well as its commits
- [X] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

2021-04-19 00:56 UTC, yungyuc requested changes
@bhbruce please update the proposal as soon as possible.

2021-04-19 00:56 UTC, yungyuc commented on proposal/bhbruce/Pytorch_INT8_GEMM.rst
> +Pyotrch INT8 convolution and linear layers for both training and inference on NVIDIA GPU to boost your Research and products come true.
Need a github repository.

2021-04-19 00:56 UTC, yungyuc commented on proposal/bhbruce/Pytorch_INT8_GEMM.rst
> +Currently, deep learning(DL) frameworks only support FP32/FP16 convolution and linear layers for training and inference. Quantizing DL model to INT8 can speed up training and infrence and decrease po
As we discussed in the classroom, it may be interesting to cover your analysis for why others use FP32 to cover the need for INT8.  You may do the research and present it without really write code for the analysis.  But it will be certainly good if you have code as your supporting materials.

2021-04-19 00:56 UTC, yungyuc commented on proposal/bhbruce/Pytorch_INT8_GEMM.rst
> +
Need architecture.

2021-04-19 00:56 UTC, yungyuc commented on proposal/bhbruce/Pytorch_INT8_GEMM.rst
> +- Engineers can use our custom plugin on edge devices which have pytorch and NVIDIA GPU. They can use our INT8 layers to perform inference or on-device learning to enhance the models.
I am not sure whether or not you have access to the GPU devices you need.  Nevertheless, accelerator hardware makes things complicated.

2021-04-19 00:56 UTC, yungyuc commented on proposal/bhbruce/Pytorch_INT8_GEMM.rst
> +Show how a user programmatically uses your system.  You are supposed to
You may add more about the API as you go.

2021-04-19 00:56 UTC, yungyuc commented on proposal/bhbruce/Pytorch_INT8_GEMM.rst
> +
Need engineering.

2021-04-19 00:56 UTC, yungyuc commented on proposal/bhbruce/Pytorch_INT8_GEMM.rst
> +
Need schedule.

2021-04-19 00:57 UTC, yungyuc commented
> @bhbruce please update the proposal as soon as possible.

I intended to provide the review last week but it stayed in my account due to mis-operation.  I apologize for making it late.  But to help your project move forward, please still update the proposal swiftly.

2021-04-20 03:08 UTC, yungyuc commented
I will finalize grading and merge today.

2021-04-20 04:24 UTC, bhbruce commented
> > @bhbruce please update the proposal as soon as possible.
> 
> I intended to provide the review last week but it stayed in my account due to mis-operation. I apologize for making it late. But to help your project move forward, please still update the proposal swiftly.

Sorry for the late reply.
Thanks for your reviews. I will not continue the project because of personal consideration and plan. I will close the pull request.
Thank you!

2021-04-20 04:24 UTC, closed without merging

2021-04-20 09:13 UTC, yungyuc commented
Thanks for letting me know.  You may still discuss with me using your own agenda rather than the requirement of the course.